#!/usr/bin/env zsh

_fav-cli-env() {
    local variables=( _fav_version \
                      _fav_root \
                      FAV_FILE \
                      FAV_WIDGET_KEY \
                      FAV_DIR_PREVIEW_CMD \
                      FAV_FILE_PREVIEW_CMD \
                      FAV_FZF_OPTIONS \
                      FAV_ENABLE_ICONS \
                      FAV_DIR_ICON \
                      FAV_FILE_ICON \
                      FAV_UNKNOWN_ICON \
                      FAV_ORDER )
    local len
    for var in $variables; do
        [[ ${#var} -gt $len ]] && len=${#var}
    done
    for var in $variables; do
        printf "%-${len}s  %s\n" "$var" "${(P)var}"
    done
}
