#!/usr/bin/env zsh

_fav-cli-add() {
    local fav_path="$PWD"
    [[ $1 == '-f' ]] && { fav_path+="/$2"; shift 2 }
    [[ -e $fav_path ]] || { echo "[ERROR] The path '$fav_path' does not exist!" >&2 && return 1 }
    local fav_name=${1:-${(L)$(basename "$fav_path")}}
    fav_name=$( sed -e 's/[^A-Za-z0-9._-]/_/g; s/^-/_/' <<< $fav_name )
    [[ -n $(hash -dm $fav_name) && -e ~$fav_name ]] &&
        { echo "[ERROR] '$fav_name' already points to" ~$fav_name "-- please, use a different name!" >&2 && return 1 }
    echo "hash -d $fav_name=\"${fav_path}\"" >> "$FAV_FILE"
    source "$FAV_FILE"
    echo "[ADDED]  $([[ -d $fav_path ]] && echo "$FAV_DIR_ICON" || echo "$FAV_FILE_ICON")  $fav_name  $fav_path"
}
