#!/usr/bin/env zsh

_fav-ls() {
    awk -F = -vD="$FAV_DIR_ICON" -vF="$FAV_FILE_ICON" -vU="$FAV_UNKNOWN_ICON" \
        '{ gsub(/^hash -d /, "", $1);
           if (system("test -e "$2)){ $1=U OFS $1; print "\033[31m"NR OFS $0"\033[0m" }
           else if (system("test -d "$2)){ $1=F OFS $1; print "\033[33m"NR OFS $0"\033[0m" }
           else { $1=D OFS $1; print "\033[34m"NR OFS $0"\033[0m" }
        }' "$FAV_FILE" |
        column -t
}
