#!/usr/bin/env zsh

_fav-ls() {
    local fav_order=${1:-${FAV_ORDER:--time}}
    local len=( $( awk -F= '{ if (length($1) > nameL) nameL = length($1) } END { print length(NR) ORS nameL-8}' "$FAV_FILE" ) )
    awk -F= -v Ui="$FAV_UNKNOWN_ICON" -v Fi="$FAV_FILE_ICON" -v Di="$FAV_DIR_ICON" -v numL="${len[1]}" -v nameL="${len[2]}" \
        'BEGIN { Ufmt = "\033[31m%-"numL"s  U  "Ui"  %-"nameL"s  %s\033[0m\n"
                 Ffmt = "\033[33m%-"numL"s  F  "Fi"  %-"nameL"s  %s\033[0m\n"
                 Dfmt = "\033[34m%-"numL"s  D  "Di"  %-"nameL"s  %s\033[0m\n"
               }
               { name = substr($1,9)
                 path = substr($0, index($0,FS)+2); sub(/"$/, "", path)
                 if      (system("test -e \""path"\"")) printf Ufmt, NR, name, path
                 else if (system("test -d \""path"\"")) printf Ffmt, NR, name, path
                 else                                   printf Dfmt, NR, name, path
               }' "$FAV_FILE" |
        case "$fav_order" in
            -type)  LC_ALL=C sort -dbi  -k2,2 -k4,4 ;;
            -rtype) LC_ALL=C sort -dbir -k2,2 -k4,4 ;;
            -name)  LC_ALL=C sort -dbi  -k4,4 ;;
            -rname) LC_ALL=C sort -dbir -k4,4 ;;
            -path)  LC_ALL=C sort -dbi  -k5 ;;
            -rpath) LC_ALL=C sort -dbir -k5 ;;
            -time)  >&1 ;;
            -rtime) LC_ALL=C sort -k1.6,1nr ;;
            *)  echo "[ERROR] Unrecognized FAV_ORDER \"$fav_order\"! Using default order \"-time\".\n" >&2
                >&1
                return 1
            ;;
        esac
}
