#!/usr/bin/env zsh

_fav-rm() {
	local removed=$( < /dev/stdin )
	local len=$( awk '{ if ( length($3) > l ) { l=length($3) } } END { print l }' <<< "$removed" )
	awk -vL3="$len" -vfav_file="$FAV_FILE" \
		'BEGIN { fmt = "[REMOVED]  %s  %-"L3"s  %s\n"
			   }
			   { gsub(/[[:cntrl:]]\[[[:digit:]]+m/, "", $0)
				 lines = lines$1"d;"
				 path = substr($0, index($0,$5))
				 printf fmt, $3, $4, path
			   }
		 END   { system("sed -i \"" lines "\" " fav_file)
			   }' <<< "$removed"
	hash -drf
	source "$FAV_FILE"
}
