#!/usr/bin/env zsh

# --with-nth = show fields from original input
# --nth = search fields from shown input
# preview param {} based on original input (re-join possibly space-split path)
_fav-panel() {
    fzf ${=FAV_FZF_OPTS} \
        --with-nth=3.. \
        --nth=2.. \
        --preview="$_fav_root/functions/_fav-preview {5..}" \
        --ansi \
        --multi \
        $@
}
