#!/usr/bin/env zsh

_fav-init() {
    FAV_DIR_PREVIEW_CMD=${FAV_DIR_PREVIEW_CMD:-$( _fav-available-cmd 'exa -lbg --git --color=always' 'ls -l' ) }
    FAV_FILE_PREVIEW_CMD=${FAV_FILE_PREVIEW_CMD:-$( _fav-available-cmd 'bat --paging=always' less more ) }
    export FAV_DIR_PREVIEW_CMD FAV_FILE_PREVIEW_CMD
    FAV_ENABLE_ICONS=${FAV_ENABLE_ICONS:-false}
    FAV_DIR_ICON=${FAV_DIR_ICON:-$($FAV_ENABLE_ICONS && echo ' ' || echo 'D')}         #     
    FAV_FILE_ICON=${FAV_FILE_ICON:-$($FAV_ENABLE_ICONS && echo ' ' || echo 'F')}       #     
    FAV_UNKNOWN_ICON=${FAV_UNKNOWN_ICON:-$($FAV_ENABLE_ICONS && echo '' || echo '?')}
}
