#!/usr/bin/env zsh

_fav-fzf() {
    fzf ${=FAV_FZF_OPTIONS} \
        --preview="$_fav_root/functions/_fav-preview {-1}" \
        --bind="alt-j:preview-down,alt-k:preview-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up" \
        --ansi \
        --multi \
        $@
}
