#!/usr/bin/env zsh

fav-widget() {
    [[ ${#${(z)BUFFER}} -eq 0 && -o auto_cd ]] && local accept=true
    LBUFFER="${LBUFFER}$( _fav-pick )"
    local ret=$?
    zle redisplay
    typeset -f zle-line-init > /dev/null && zle zle-line-init
    [[ $ret -eq 0 && -n $BUFFER && -n $accept ]] && zle .accept-line
    return $ret
}
